version: '3.8'

services:
  web:
    container_name: serverbot-web
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev